sonar.projectKey=cloudcart
sonar.projectName=CloudCart
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/uploads/**

sonar.python.version=3.7
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
