sonar.projectKey=cloudcart-backend
sonar.projectName=cloudcart-backend
sonar.projectVersion=1.0

sonar.sources=backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/uploads/**

sonar.python.version=3.11

sonar.sourceEncoding=UTF-8