sonar.projectKey=cloudcart-frontend
sonar.projectName=cloudcart-frontend
sonar.projectVersion=1.0

sonar.sources=frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/uploads/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8