# Grafana datasource provisioning (not Prometheus server config)
# https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
