apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.global.namespace | default "cloudcart" }}
type: Opaque
data:
  # Values must be base64 encoded
  # Generate: echo -n "value" | base64
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.db.username .Values.db.password .Values.db.host .Values.db.port .Values.db.database | b64enc }}
  SECRET_KEY: {{ .Values.secretKey | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc }}
