apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-seed-{{ .Release.Revision }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed-db
          image: postgres:13
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for PostgreSQL..."

              until pg_isready \
                -h postgres \
                -U {{ .Values.username }}
              do
                sleep 5
              done

              echo "Seeding database..."

              psql \
                -h postgres \
                -U {{ .Values.username }} \
                -d {{ .Values.database }} \
                -f /seed/seed.sql
          volumeMounts:
            - name: seed-sql
              mountPath: /seed
      volumes:
        - name: seed-sql
          configMap:
            name: db-seed-sql