apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  type: {{ .Values.service.type }}
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5432
